version: "3.9"

volumes:
  simulator-build:

services:
  simulator:
    build:
      context: .
      target: prod
    ports:
      - 9000:80
      - 9001:9001
    tty: true
    volumes:
      - ./data:/data
