version: "3.9"

volumes:
  simulator-build:

services:
  simulator:
    image: localhost:5000/dmfro/dynaminator:latest
    ports:
      - 9000:80
      - 9001:9001
    tty: true
    volumes:
      - ./data:/data
    environment:
      HTTP_HOST: localhost:9000
      WS_HOST: localhost:9001
