version: "3.9"

volumes:
  simulator-build:

services:
  simulator:
    image: localhost:5000/dynaminator/dynaminator:latest
    ports:
      - 8000:80
    tty: true
    volumes:
      - ./data:/data
