version: "3.9"

volumes:
  simulator-build:

services:
  simulator:
    build:
      context: .
      target: dev
    ports:
      - 9000:80
      - 9001:9001
    tty: true
    volumes:
      - ./app:/app
      - simulator-build:/tmp/app/build
      - ./web/swagger:/swagger
      - ./data:/data
    command: /run.dev.sh
