name: Benchmark

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmfro/dynaminator-testenv

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ../app -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build .
  
    - name: Run benchmarks
      run: |
        cd build
        tests "[fw-large],[cfw-large],[ie]" --rng-seed 0 --baseDir ../ benchmarkDir /
