name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install prerequisites with apt
      run : |
        sudo apt-get install -y nlohmann-json-dev

    - name: Install prerequisites
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2/
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install

    - name: Build
      run: |
        cd app
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Test
      run: |
        app/build/tests
