name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install prerequisites with apt
      run : |
        sudo apt-get update
        sudo apt-get install -y nlohmann-json3-dev

    - name: Install prerequisites
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2/
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install

    - name: Get assets
      run: |
        cd app
        mkdir -p data/network
        mkdir -p data/od
        curl -L https://www.dropbox.com/s/5hwruycfaulksa3/net.net.xml --output data/network/net.net.xml
        curl -L https://www.dropbox.com/s/y1obv0hitxysvqk/taz.xml --output data/network/taz.xml
        curl -L https://www.dropbox.com/s/pvyefk7ewyssprf/matrix.8.0.9.0.1.fma --output data/od/matrix.8.0.9.0.1.fma

    - name: Build
      run: |
        cd app
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Test
      run: |
        app/build/tests
