name: Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        target: prod
        push: true
        tags: "${{ vars.DOCKERHUB_ID }}/${{ vars.DOCKERHUB_IMG }}:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Get assets
      run: |
        cd app
        mkdir -p data/network
        mkdir -p data/od
        curl -L https://www.dropbox.com/s/5hwruycfaulksa3/net.net.xml --output data/network/net.net.xml
        curl -L https://www.dropbox.com/s/y1obv0hitxysvqk/taz.xml --output data/network/taz.xml
        curl -L https://www.dropbox.com/s/pvyefk7ewyssprf/matrix.8.0.9.0.1.fma --output data/od/matrix.8.0.9.0.1.fma

    - name: Integration testing
      run: |
        mkdir -p data/out
        chmod +x test/test_*.py
        docker-compose -f docker-compose.test.yml up -d
        sleep 10
        test/test_StaticSimulation.py
        ls -la
        ls -la data
        ls -la data/out
