name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmfro/dynaminator-testenv

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: |
        cd app
        mkdir build
        cd build
        cmake .. -DCOVERAGE
        cmake --build .

    - name: Test
      run: |
        cd app
        build/tests

    - name: Coverage report
      run: |
        lcov --capture --directory . --output-file main_coverage.info
        genhtml main_coverage.info --output-directory out      
