name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmfro/dynaminator-testenv

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Build
      run: |
        cd app
        mkdir -p build
        cd build
        ls -la
        cmake .. -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCOVERAGE=1
        cmake --build .

    - uses: actions/upload-artifact@v2
      with:
        name: executables
        path: |
          app/build/dynaminator
          app/build/tests

    - name: Test
      run: |
        cd app
        build/tests --baseDir /

    - name: Coverage report
      run: |
        lcov --capture --directory . --output-file main_coverage.info
        genhtml main_coverage.info --output-directory out      

    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: out
