name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmfro/dynaminator-testenv

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ../app -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCOVERAGE=1 -DTESTS_BASEDIR=../ -DTESTS_BENCHMARKDIR=/
        cmake --build .

    - name: Upload executables artifact
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: |
          build/dynaminator
          build/tests

    - name: Test with coverage
      run: |
        cmake --build build/ --target coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: build/coverage

    - name: Upload coverage report (GitHub Pages-ready)
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: build/coverage

  deploy-gh-pages:
    # Add a dependency to the build job
    needs: build

    if: github.ref == 'refs/heads/master'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1