name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install prerequisites with apt
      run : |
        sudo apt-get update
        sudo apt-get install -y \
          nlohmann-json3-dev \
          libwebsocketpp-dev libasio-dev

    - name: Install prerequisites
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2/
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install

    - name: Get assets
      run: |
        cd app
        mkdir -p data/network
        mkdir -p data/network/crossroads1
        mkdir -p data/network/crossroads2
        mkdir -p data/od
        mkdir -p data/out
        curl -L https://www.dropbox.com/s/5hwruycfaulksa3/net.net.xml --output data/network/net.net.xml
        curl -L https://www.dropbox.com/s/y1obv0hitxysvqk/taz.xml --output data/network/taz.xml
        curl -L https://www.dropbox.com/s/oobwk5bi4qew4np/matrix.9.0.10.0.2.fma --output data/od/matrix.9.0.10.0.2.fma
        curl -L https://www.dropbox.com/s/1v3hzyoyest33wi/crossroads1.net.xml --output data/network/crossroads1/crossroads1.net.xml
        curl -L https://www.dropbox.com/s/cz5qvgwofby6x6r/crossroads2.net.xml --output data/network/crossroads2/crossroads2.net.xml

    - name: Build
      run: |
        cd app
        mkdir build
        cd build
        cmake .. -DCOVERAGE
        cmake --build .

    - name: Test
      run: |
        cd app
        build/tests

    - name: Coverage report
      run: |
        lcov --capture --directory . --output-file main_coverage.info
        genhtml main_coverage.info --output-directory out      
