name: Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmfro/dynaminator-testenv

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ../app -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCOVERAGE=1
        cmake --build .

    - name: Upload executables artifact
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: |
          build/dynaminator
          build/tests

    - name: Test with coverage
      run: |
        cd build
        cmake --build . --target coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: build/coverage
